version: 2.1

executors:
  default:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.go-version >>
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/skanehira/docui
  docker:
    parameters:
      go-version:
        type: string
    docker:
      - image: golang:<< parameters.go-version >>
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/skanehira/docui

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  build:
    parameters:
      go-version:
        type: string
    executor:
      name: default
      go-version: << parameters.go-version >>
    steps:
      - checkout
      - go_mod_download

      - run:
          name: Run build
          command: go build
  lint:
    parameters:
      go-version:
        type: string
    executor:
      name: default
      go-version: << parameters.go-version >>
    steps:
      - checkout

      - run:
          name: Install golint
          command: go get github.com/golang/lint/golint

      - run:
          name: Run golint
          command: golint -set_exit_status=1 ./...
  build-docker-image:
    parameters:
      go-version:
        type: string
    executor:
      name: default
      go-version: << parameters.go-version >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.0"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          docker build -t skanehira/docui:$TAG .

workflows:
  stable-build:
    jobs:
      - lint:
          go-version: "1.11.4"
      - build:
          go-version: "1.11.4"
          requires:
            - lint
  latest-build:
    jobs:
      - lint:
          go-version: "1.11.5"
      - build:
          go-version: "1.11.5"
          requires:
            - lint
  docker-image:
    jobs:
      - build-docker-image:
          go-version: "1.11.5"